# Generated by Django 5.1.6 on 2025-02-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Parent',
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='Staf',
        ),
    ]
